<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        $orders = [
            [
                'sl_no' => '1',
                'ki_id' => 'KIC-001-MW-MEL-STC',
                'order_received' => '2026-07-02',
                'region' => 'CENTRAL',
                'city' => 'QASSIM',
                'circuit_id' => 'QASSIM-RIYADH DIAS11003',
                'order_number' => 'I14977452579171',
                'customer_name' => 'Fosam Limited Company',
                'customer_contact' => 'ابتسام اليامي - 553584472',
                'bw' => '20MBPs',
                'los_performed' => '2026-07-05',
                'los_status' => 'CLOS',
                'los_id' => '601-22-000',
                'cwo_date' => '2026-07-13',
                'order_status' => 'Under MW Installation',
                'assigned_to' => 'Haroon',
                'is_cancelled' => false,
                'priority' => 'High',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sl_no' => '2',
                'ki_id' => 'KIC-002-MW-MEL-STC',
                'order_received' => '2026-07-02',
                'region' => 'CENTRAL',
                'city' => 'RIYADHDST',
                'circuit_id' => 'RIYADHDST-RIYADH DIAS11019',
                'order_number' => 'I14977108106221',
                'customer_name' => 'Bunyan for Industry CompanySole Partnership',
                'customer_contact' => 'وليد الغامدي - 565577234',
                'bw' => '25MBPs',
                'los_performed' => '2026-07-05',
                'los_status' => 'CLOS',
                'los_id' => 'ZAKA160',
                'cwo_date' => '2026-07-13',
                'installation_start' => '2026-07-23',
                'installation_complete' => '2026-07-25',
                'delivery_date' => '2026-07-25',
                'order_status' => 'Delivered /CR Pending',
                'assigned_to' => 'Haroon',
                'is_cancelled' => false,
                'priority' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sl_no' => '3',
                'ki_id' => 'KIC-003-MW-MEL-STC',
                'order_received' => '2026-07-08',
                'region' => 'CENTRAL',
                'city' => 'RIYADHDST',
                'circuit_id' => 'RIYADHDST-RIYADH DIAS11048',
                'order_number' => 'I14978406074781',
                'customer_name' => 'MINISTRY OF ISLAMIC AFFAIRS1',
                'customer_contact' => 'mutlatq mutlatq- 554141990',
                'bw' => '6MBPs',
                'los_performed' => '2026-07-09',
                'los_status' => 'CLOS',
                'los_id' => 'ZTMA001',
                'cwo_date' => '2026-07-19',
                'installation_start' => '2026-07-25',
                'installation_complete' => '2026-07-26',
                'delivery_date' => '2026-07-26',
                'order_status' => 'Delivered ',
                'assigned_to' => 'Shukoor',
                'is_cancelled' => false,
                'priority' => 'High',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sl_no' => '4',
                'ki_id' => 'KIC-004-MW-MEL-STC',
                'order_received' => '2026-07-08',
                'region' => 'CENTRAL',
                'city' => 'QASSIM',
                'circuit_id' => 'QASSIM-RIYADH DIAS11007',
                'order_number' => 'I14978403932431',
                'customer_name' => 'MINISTRY OF ISLAMIC AFFAIRS1',
                'customer_contact' => 'mutlatq mutlatq- 554141990/+966561733000فواز الوتيد دوام',
                'bw' => '6MBPs',
                'los_performed' => '2026-07-13',
                'los_status' => 'CLOS',
                'los_id' => 'ZBRA012',
                'cwo_date' => '2026-07-27',
                'order_status' => 'Under MW Installation',
                'assigned_to' => 'Haroon',
                'is_cancelled' => false,
                'priority' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sl_no' => '5',
                'ki_id' => 'KIC-005-MW-MEL-STC',
                'order_received' => '2026-07-10',
                'region' => 'CENTRAL',
                'city' => 'QASSIM',
                'circuit_id' => 'QASSIM-RIYADH W-DIA64771',
                'order_number' => 'I-154546342-0886',
                'customer_name' => 'NOURNET ISP 1',
                'customer_contact' => 'Atif Ahmad - 966504164527',
                'bw' => '8MBPs',
                'los_performed' => '2026-07-13',
                'los_status' => 'CLOS',
                'los_id' => 'ZBDA012',
                'order_status' => 'Under Activation',
                'assigned_to' => null,
                'is_cancelled' => false,
                'priority' => 'Medium',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sl_no' => '18',
                'ki_id' => 'KIC-018-MW-MEL-STC',
                'order_received' => '2026-07-16',
                'region' => 'CENTRAL',
                'city' => 'RIYADH',
                'circuit_id' => 'RIYADH-RIYADH W-DIA65391',
                'order_number' => 'I-155156872-9273',
                'customer_name' => 'NOURNET ISP 1',
                'customer_contact' => 'Atif Ahmad - 966504164527',
                'bw' => '8MBPs',
                'los_performed' => '2026-07-20',
                'los_status' => 'CLOS',
                'los_id' => 'ZAKA013',
                'order_status' => 'Cancelled',
                'assigned_to' => null,
                'is_cancelled' => true,
                'priority' => 'Low',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('orders')->insert($orders);
    }
}
